DROP DATABASE IF EXISTS books;
CREATE DATABASE books
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
USE books;
CREATE TABLE authors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    country VARCHAR(100),
    birth_year INT
);
CREATE TABLE books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL,
    language VARCHAR(100),
    year INT,
    authorID INT,
    FOREIGN KEY (authorID) REFERENCES authors(id)
);
INSERT INTO authors (author, image, country, birth_year) VALUES
('Chinua Achebe', 'images/authors/Chinua_Achebe.jpg', 'Nigeria', 1930),
('Hans Christian Andersen', 'images/authors/Hans_Christian_Andersen.jpg', 'Denmark', 1805),
('Dante Alighieri', 'images/authors/Dante_Alighieri.jpg', 'Italy', 1265),
('Melanie Lee Robbins', 'images/authors/Melanie_Lee_Robbins.jpg', 'U.S', 1968),
('Jane Austen', 'images/authors/Jane_Austen.jpg', 'United Kingdom', 1775),
('Honoré de Balzac', 'images/authors/Honoré_de_Balzac.jpg', 'France', 1799),
('Samuel Beckett', 'images/authors/Samuel_Beckett.jpg', 'Ireland', 1906),
('Giovanni Boccaccio', 'images/authors/Giovanni_Boccaccio.jpg', 'Italy', 1313),
('Jorge Luis Borges', 'images/authors/Jorge_Luis_Borges.jpg', 'Argentina', 1899),
('Emily Brontë', 'images/authors/Emily_Brontë.jpg', 'United Kingdom', 1818),
('Albert Camus', 'images/authors/Albert_Camus.jpg', 'France', 1913),
('Paul Celan', 'images/authors/Paul_Celan.jpg', 'Romania', 1920),
('Louis-Ferdinand Céline', 'images/authors/Louis_Ferdinand_Céline.jpg', 'France', 1894),
('Miguel de Cervantes', 'images/authors/Miguel_de_Cervantes.jpg', 'Spain', 1547),
('Geoffrey Chaucer', 'images/authors/Geoffrey_Chaucer.jpg', 'United Kingdom', 1343),
('Anton Chekhov', 'images/authors/Anton_Chekhov.jpg', 'Russia', 1860),
('Joseph Conrad', 'images/authors/Joseph_Conrad.jpg', 'Poland', 1857),
('Charles Dickens', 'images/authors/Charles_Dickens.jpg', 'United Kingdom', 1812),
('Denis Diderot', 'images/authors/Denis_Diderot.jpg', 'France', 1713),
('Alfred Döblin', 'images/authors/Alfred_Döblin.jpg', 'Germany', 1878),
('Fyodor Dostoevsky', 'images/authors/Fyodor_Dostoevsky.jpg', 'Russia', 1821),
('George Eliot', 'images/authors/George_Eliot.jpg', 'United Kingdom', 1819),
('Ralph Ellison', 'images/authors/Ralph_Ellison.jpg', 'United States', 1914),
('Euripides', 'images/authors/Euripides.jpg', 'Greece', -480),
('William Faulkner', 'images/authors/William_Faulkner.jpg', 'United States', 1897),
('Gustave Flaubert', 'images/authors/Gustave_Flaubert.jpg', 'France', 1821),
('Federico García Lorca', 'images/authors/Federico_García_Lorca.jpg', 'Spain', 1898),
('Gabriel García Márquez', 'images/authors/Gabriel_García_Márquez.jpg', 'Colombia', 1927),
('Johann Wolfgang von Goethe', 'images/authors/', 'Germany', 1749),
('Nikolai Gogol', 'images/authors/', 'Ukraine', 1809),
('Günter Grass', 'images/authors/', 'Germany', 1927),
('João Guimarães Rosa', 'images/authors/', 'Brazil', 1908),
('Knut Hamsun', 'images/authors/', 'Norway', 1859),
('Ernest Hemingway', 'images/authors/', 'United States', 1899),
('Homer', 'images/authors/', 'Greece', NULL),
('Henrik Ibsen', 'images/authors/', 'Norway', 1828),
('James Joyce', 'images/authors/', 'Ireland', 1882),
('Franz Kafka', 'images/authors/', 'Czech Republic', 1883),
('Kālidāsa', 'images/authors/', 'India', NULL),
('Yasunari Kawabata', 'images/authors/', 'Japan', 1899),
('Nikos Kazantzakis', 'images/authors/', 'Greece', 1883),
('D. H. Lawrence', 'images/authors/', 'United Kingdom', 1885),
('Halldór Laxness', 'images/authors/', 'Iceland', 1902),
('Giacomo Leopardi', 'images/authors/', 'Italy', 1798),
('Doris Lessing', 'images/authors/', 'United Kingdom', 1919),
('Astrid Lindgren', 'images/authors/', 'Sweden', 1907),
('Lu Xun', 'images/authors/', 'China', 1881),
('Naguib Mahfouz', 'images/authors/', 'Egypt', 1911),
('Thomas Mann', 'images/authors/', 'Germany', 1875),
('Herman Melville', 'images/authors/', 'United States', 1819),
('Michel de Montaigne', 'images/authors/', 'France', 1533),
('Elsa Morante', 'images/authors/', 'Italy', 1912),
('Toni Morrison', 'images/authors/', 'United States', 1931),
('Murasaki Shikibu', 'images/authors/', 'Japan', 973),
('Robert Musil', 'images/authors/', 'Austria', 1880),
('Vladimir Nabokov', 'images/authors/', 'Russia', 1899),
('George Orwell', 'images/authors/', 'United Kingdom', 1903),
('Ovid', 'images/authors/', 'Roman Empire', -43),
('Fernando Pessoa', 'images/authors/', 'Portugal', 1888),
('Edgar Allan Poe', 'images/authors/', 'United States', 1809),
('Marcel Proust', 'images/authors/', 'France', 1871),
('François Rabelais', 'images/authors/', 'France', 1494),
('Juan Rulfo', 'images/authors/', 'Mexico', 1917),
('Rumi', 'images/authors/', 'Persia', 1207),
('Salman Rushdie', 'images/authors/', 'India', 1947),
('Saadi', 'images/authors/', 'Persia', 1210),
('Tayeb Salih', 'images/authors/', 'Sudan', 1929),
('José Saramago', 'images/authors/', 'Portugal', 1922),
('William Shakespeare', 'images/authors/', 'United Kingdom', 1564),
('Sophocles', 'images/authors/', 'Greece', -497),
('Stendhal', 'images/authors/', 'France', 1783),
('Laurence Sterne', 'images/authors/', 'Ireland', 1713),
('Italo Svevo', 'images/authors/', 'Italy', 1861),
('Jonathan Swift', 'images/authors/', 'Ireland', 1667),
('Leo Tolstoy', 'images/authors/', 'Russia', 1828),
('Mark Twain', 'images/authors/', 'United States', 1835),
('Valmiki', 'images/authors/', 'India', NULL),
('Virgil', 'images/authors/Virgil.jpg', 'Roman Empire', -70),
('Vyasa', 'images/authors/Vyasa.jpg', 'India', NULL),
('Walt Whitman', 'images/authors/', 'United States', 1819),
('Virginia Woolf', 'images/authors/Virginia_Woolf.jpg', 'United Kingdom', 1882),
('Marguerite Yourcenar', 'images/authors/Marguerite_Yourcenar.jpg', 'Belgium', 1903);
INSERT INTO books (title, image, language,year, authorID) VALUES
('Things Fall Apart', 'images/books/things-fall-apart.jpg', 'English', 1958, 1),
('No Longer at Ease', 'images/books/no-longer-at-ease.jpg', 'English', 1960, 1),
('Arrow of God', 'images/books/arrow-of-god.jpg', 'English', 1964, 1),
('A Man of the People', 'images/books/a-man-of-the-people.jpg', 'English', 1966, 1),
('Anthills of the Savannah', 'images/books/anthills-of-the-savannah.jpg', 'English', 1987, 1),
('The Sacrificial Egg and Other Stories', 'images/books/sacrificial-egg.jpg', 'English', 1962, 1),
('Girls at War and Other Stories', 'images/books/girls-at-war.jpg', 'English', 1973, 1),
('Chike and the River', 'images/books/chike-and-the-river.jpg', 'English', 1966, 1),
('How the Leopard Got His Claws', 'images/books/leopard-claws.jpg', 'English', 1972, 1),
('The Drum', 'images/books/the-drum.jpg', 'English', 1977, 1),
('The Flute', 'images/books/the-flute.jpg', 'English', 1977, 1),
('Beware, Soul Brother', 'images/books/beware-soul-brother.jpg', 'English', 1971, 1),
('Christmas in Biafra and Other Poems', 'images/books/christmas-in-biafra.jpg', 'English', 1973, 1),
('Morning Yet on Creation Day', 'images/books/morning-yet-on-creation-day.jpg', 'English', 1975, 1),
('The Trouble with Nigeria', 'images/books/trouble-with-nigeria.jpg', 'English', 1983, 1),
('Hopes and Impediments', 'images/books/hopes-and-impediments.jpg', 'English', 1988, 1),
('Home and Exile', 'images/books/home-and-exile.jpg', 'English', 2000, 1),
('There Was a Country', 'images/books/there-was-a-country.jpg', 'English', 2012, 1),
('The Tinder-Box', 'images/books/tinder-box.jpg', 'Danish', 1835, 2),
('Little Claus and Big Claus', 'images/books/little-claus-big-claus.jpg', 'Danish', 1835, 2),
('The Princess and the Pea', 'images/books/princess-and-the-pea.jpg', 'Danish', 1835, 2),
('Little Ida`s Flowers', 'images/books/little-idas-flowers.jpg', 'Danish', 1835, 2),
('Thumbelina', 'images/books/thumbelina.jpg', 'Danish', 1835, 2),
('The Naughty Boy', 'images/books/naughty-boy.jpg', 'Danish', 1835, 2),
('The Travelling Companion', 'images/books/travelling-companion.jpg', 'Danish', 1835, 2),
('The Little Mermaid', 'images/books/little-mermaid.jpg', 'Danish', 1836, 2),
('The Emperor`s New Clothes', 'images/books/emperors-new-clothes.jpg', 'Danish', 1837, 2),
('The Galoshes of Fortune', 'images/books/galoshes-of-fortune.jpg', 'Danish', 1838, 2),
('The Daisy', 'images/books/daisy.jpg', 'Danish', 1838, 2),
('The Steadfast Tin Soldier', 'images/books/tin-soldier.jpg', 'Danish', 1838, 2),
('The Wild Swans', 'images/books/wild-swans.jpg', 'Danish', 1838, 2),
('The Garden of Paradise', 'images/books/garden-of-paradise.jpg', 'Danish', 1838, 2),
('The Flying Trunk', 'images/books/flying-trunk.jpg', 'Danish', 1839, 2),
('The Storks', 'images/books/storks.jpg', 'Danish', 1839, 2),
('The Wicked Prince', 'images/books/wicked-prince.jpg', 'Danish', 1840, 2),
('Book of Pictures Without Pictures', 'images/books/pictures-without-pictures.jpg', 'Danish', 1840, 2),
('Ole Lukøje', 'images/books/ole-lukoje.jpg', 'Danish', 1841, 2),
('The Swineherd', 'images/books/swineherd.jpg', 'Danish', 1841, 2),
('The Buckwheat', 'images/books/buckwheat.jpg', 'Danish', 1841, 2),
('The Angel', 'images/books/angel.jpg', 'Danish', 1841, 2),
('The Nightingale', 'images/books/nightingale.jpg', 'Danish', 1842, 2),

('The Ugly Duckling', 'images/books/ugly-duckling.jpg', 'Danish', 1842, 2),
('The Fir Tree', 'images/books/fir-tree.jpg', 'Danish', 1842, 2),
('The Snow Queen', 'images/books/snow-queen.jpg', 'Danish', 1842, 2),
('The Red Shoes', 'images/books/red-shoes.jpg', 'Danish', 1843, 2),
('The Jumpers', 'images/books/jumpers.jpg', 'Danish', 1843, 2),
('The Shepherdess and the Chimney Sweep', 'images/books/shepherdess-chimney-sweep.jpg', 'Danish', 1844, 2),
('Holger the Dane', 'images/books/holger-the-dane.jpg', 'Danish', 1844, 2),
('The Little Match Girl', 'images/books/little-match-girl.jpg', 'Danish', 1844, 2),
('The Bell', 'images/books/bell.jpg', 'Danish', 1845, 2),
('The Elfin Mound', 'images/books/elfin-mound.jpg', 'Danish', 1845, 2),
('The Old House', 'images/books/old-house.jpg', 'Danish', 1845, 2),
('The Happy Family', 'images/books/happy-family.jpg', 'Danish', 1845, 2),
('The Shadow', 'images/books/shadow.jpg', 'Danish', 1845, 2),
('The Mother', 'images/books/mother.jpg', 'Danish', 1845, 2),
('The Story of a Mother', 'images/books/story-of-a-mother.jpg', 'Danish', 1846, 2),
('The Collar', 'images/books/collar.jpg', 'Danish', 1846, 2),
('The Drop of Water', 'images/books/drop-of-water.jpg', 'Danish', 1847, 2),
('The Little Tuk', 'images/books/little-tuk.jpg', 'Danish', 1847, 2),
('The Shirt Collar', 'images/books/shirt-collar.jpg', 'Danish', 1847, 2),
('The Flax', 'images/books/flax.jpg', 'Danish', 1848, 2),
('The Phoenix Bird', 'images/books/phoenix-bird.jpg', 'Danish', 1848, 2),
('A Story', 'images/books/a-story.jpg', 'Danish', 1848, 2),
('The Marsh King`s Daughter', 'images/books/marsh-kings-daughter.jpg', 'Danish', 1848, 2),
('Fairy tales', 'images/books/fairy-tales.jpg', 'Danish', 1836, 2),

('The Divine Comedy', 'images/books/the-divine-comedy.jpg', 'Italian', 1315, 3),
('The Let Them Theory', 'images/books/The_Let_Them_Theory.jpeg', 'English', 2024, 4),
('Pride and Prejudice', 'images/books/pride-and-prejudice.jpg', 'English', 1813, 5),
('Le Père Goriot', 'images/books/le-pere-goriot.jpg', 'French', 1835, 6),
('Molloy, Malone Dies, The Unnamable, the trilogy', 'images/books/molloy-malone-dies-the-unnamable.jpg', 'French, English', 1952, 7),
('The Decameron', 'images/books/the-decameron.jpg', 'Italian', 1351, 8),
('Ficciones', 'images/books/ficciones.jpg', 'Spanish', 1965, 9),
('Wuthering Heights', 'images/books/wuthering-heights.jpg', 'English', 1847, 10),
('The Stranger', 'images/books/l-etranger.jpg', 'French', 1942, 11),
('Poems', 'images/books/poems-paul-celan.jpg', 'German', 1952, 12),
('Journey to the End of the Night', 'images/books/voyage-au-bout-de-la-nuit.jpg', 'French', 1932, 13),
('Don Quijote De La Mancha', 'images/books/don-quijote-de-la-mancha.jpg', 'Spanish', 1610, 14),
('The Canterbury Tales', 'images/books/the-canterbury-tales.jpg', 'English', 1450, 15),
('Stories', 'images/books/stories-of-anton-chekhov.jpg', 'Russian', 1886, 16),
('Nostromo', 'images/books/nostromo.jpg', 'English', 1904, 17),
('Great Expectations', 'images/books/great-expectations.jpg', 'English', 1861, 18),
('Jacques the Fatalist', 'images/books/jacques-the-fatalist.jpg', 'French', 1796, 19),
('Berlin Alexanderplatz', 'images/books/berlin-alexanderplatz.jpg', 'German', 1929, 20),
('Crime and Punishment', 'images/books/crime-and-punishment.jpg', 'Russian', 1866, 21),
('The Idiot', 'images/books/the-idiot.jpg', 'Russian', 1869, 21),
('The Possessed', 'images/books/the-possessed.jpg', 'Russian', 1872, 21),
('The Brothers Karamazov', 'images/books/the-brothers-karamazov.jpg', 'Russian', 1880, 21),
('Middlemarch', 'images/books/middlemarch.jpg', 'English', 1871, 22),
('Invisible Man', 'images/books/invisible-man.jpg', 'English', 1952, 23),
('Medea', 'images/books/medea.jpg', 'Greek', -431, 24),
('Absalom, Absalom!', 'images/books/absalom-absalom.jpg', 'English', 1936, 25),
('The Sound and the Fury', 'images/books/the-sound-and-the-fury.jpg', 'English', 1929, 25),
('Madame Bovary', 'images/books/madame-bovary.jpg', 'French', 1857, 26),
('Sentimental Education', 'images/books/l-education-sentimentale.jpg', 'French', 1869, 26),
('Gypsy Ballads', 'images/books/gypsy-ballads.jpg', 'Spanish', 1928, 27),
('One Hundred Years of Solitude', 'images/books/one-hundred-years-of-solitude.jpg', 'Spanish', 1967, 28),
('Love in the Time of Cholera', 'images/books/love-in-the-time-of-cholera.jpg', 'Spanish', 1985, 28),
('Faust', 'images/books/faust.jpg', 'German', 1832, 29),
('Dead Souls', 'images/books/dead-souls.jpg', 'Russian', 1842, 30),
('The Tin Drum', 'images/books/the-tin-drum.jpg', 'German', 1959, 31),
('The Devil to Pay in the Backlands', 'images/books/the-devil-to-pay-in-the-backlands.jpg', 'Portuguese', 1956, 32),
('Hunger', 'images/books/hunger.jpg', 'Norwegian', 1890, 33),
('The Old Man and the Sea', 'images/books/the-old-man-and-the-sea.jpg', 'English', 1952, 34),
('Iliad', 'images/books/the-iliad-of-homer.jpg', 'Greek', -735, 35),
('Odyssey', 'images/books/the-odyssey-of-homer.jpg', 'Greek', -800, 35),
('A Doll`s House', 'images/books/a-Dolls-house.jpg', 'Norwegian', 1879, 36),
('Ulysses', 'images/books/ulysses.jpg', 'English', 1922, 37),
('Stories', 'images/books/stories-of-franz-kafka.jpg', 'German', 1924, 38),
('The Trial', 'images/books/the-trial.jpg', 'German', 1925, 38),
('The Castle', 'images/books/the-castle.jpg', 'German', 1926, 38),
('The recognition of Shakuntala', 'images/books/the-recognition-of-shakuntala.jpg', 'Sanskrit', 150, 39),
('The Sound of the Mountain', 'images/books/the-sound-of-the-mountain.jpg', 'Japanese', 1954, 40),
('Zorba the Greek', 'images/books/zorba-the-greek.jpg', 'Greek', 1946, 41),
('Sons and Lovers', 'images/books/sons-and-lovers.jpg', 'English', 1913, 42),
('Independent People', 'images/books/independent-people.jpg', 'Icelandic', 1934, 43),
('Poems', 'images/books/poems-giacomo-leopardi.jpg', 'Italian', 1818, 44),
('The Golden Notebook', 'images/books/the-golden-notebook.jpg', 'English', 1962, 45),
('Pippi Longstocking', 'images/books/pippi-longstocking.jpg', 'Swedish', 1945, 46),
('Diary of a Madman', 'images/books/diary-of-a-madman.jpg', 'Chinese', 1918, 47),
('Children of Gebelawi', 'images/books/children-of-gebelawi.jpg', 'Arabic', 1959, 48),
('Buddenbrooks', 'images/books/buddenbrooks.jpg', 'German', 1901, 49),
('The Magic Mountain', 'images/books/the-magic-mountain.jpg', 'German', 1924, 49),
('Moby Dick', 'images/books/moby-dick.jpg', 'English', 1851, 50),
('Essays', 'images/books/essais.jpg', 'French', 1595, 51),
('History', 'images/books/history.jpg', 'Italian', 1974, 52),
('Beloved', 'images/books/beloved.jpg', 'English', 1987, 53),
('The Tale of Genji', 'images/books/the-tale-of-genji.jpg', 'Japanese', 1006, 54),
('The Man Without Qualities', 'images/books/the-man-without-qualities.jpg', 'German', 1931, 55),
('Lolita', 'images/books/lolita.jpg', 'English', 1955, 56),
('Nineteen Eighty-Four', 'images/books/nineteen-eighty-four.jpg', 'English', 1949, 57),
('Metamorphoses', 'images/books/the-metamorphoses-of-ovid.jpg', 'Classical Latin', 100, 58),
('The Book of Disquiet', 'images/books/the-book-of-disquiet.jpg', 'Portuguese', 1928, 59),
('Tales', 'images/books/tales-and-poems-of-edgar-allan-poe.jpg', 'English', 1950, 60),
('In Search of Lost Time', 'images/books/a-la-recherche-du-temps-perdu.jpg', 'French', 1920, 61),
('Gargantua and Pantagruel', 'images/books/gargantua-and-pantagruel.jpg', 'French', 1533, 62),
('Pedro Páramo', 'images/books/pedro-paramo.jpg', 'Spanish', 1955, 63),
('The Masnavi', 'images/books/the-masnavi.jpg', 'Persian', 1236, 64),
('Midnight`s Children', 'images/books/midnights-children.jpg', 'English', 1981, 65),
('Bostan', 'images/books/bostan.jpg', 'Persian', 1257, 66),
('Season of Migration to the North', 'images/books/season-of-migration-to-the-north.jpg', 'Arabic', 1966, 67),
('Blindness', 'images/books/blindness.jpg', 'Portuguese', 1995, 68),
('Hamlet', 'images/books/hamlet.jpg', 'English', 1603, 69),
('King Lear', 'images/books/king-lear.jpg', 'English', 1608, 69),
('Othello', 'images/books/othello.jpg', 'English', 1609, 69),
('Oedipus the King', 'images/books/oedipus-the-king.jpg', 'Greek', -430, 70),
('The Red and the Black', 'images/books/le-rouge-et-le-noir.jpg', 'French', 1830, 71),
('The Life And Opinions of Tristram Shandy', 'images/books/the-life-and-opinions-of-tristram-shandy.jpg', 'English', 1760, 72),
('Confessions of Zeno', 'images/books/confessions-of-zeno.jpg', 'Italian', 1923, 73),
('Gulliver`s Travels', 'images/books/gullivers-travels.jpg', 'English', 1726, 74),
('War and Peace', 'images/books/war-and-peace.jpg', 'Russian', 1867, 75),
('Anna Karenina', 'images/books/anna-karenina.jpg', 'Russian', 1877, 75),
('The Death of Ivan Ilyich', 'images/books/the-death-of-ivan-ilyich.jpg', 'Russian', 1886, 75),
('The Adventures of Huckleberry Finn', 'images/books/the-adventures-of-huckleberry-finn.jpg', 'English', 1884, 76),
('Ramayana', 'images/books/ramayana.jpg', 'Sanskrit', -450, 77),
('The Aeneid', 'images/books/the-aeneid.jpg', 'Classical Latin', -23, 78),
('Mahabharata', 'images/books/the-mahab-harata.jpg', 'Sanskrit', -700, 79),
('Leaves of Grass', 'images/books/leaves-of-grass.jpg', 'English', 1855, 80),
('Mrs Dalloway', 'images/books/mrs-dalloway.jpg', 'English', 1925, 81),
('To the Lighthouse', 'images/books/to-the-lighthouse.jpg', 'English', 1927, 81),
('Memoirs of Hadrian', 'images/books/memoirs-of-hadrian.jpg', 'French', 1951, 82),
('The Epic Of Gilgamesh', 'images/books/the-epic-of-gilgamesh.jpg', 'Akkadian', -1700, null),
('The Book Of Job', 'images/books/the-book-of-job.jpg', 'Hebrew', -600, null),
('One Thousand and One Nights', 'images/books/one-thousand-and-one-nights.jpg', 'Arabic', 1200, null),
('Njál`s Saga', 'images/books/njals-saga.jpg', 'Old Norse', 1350, null);

SELECT
    b.id,
    b.title,
    b.image AS book_image,
    b.language,
    b.year,
    a.author,
    a.image AS author_image,
    a.country,
    a.birth_year
FROM books AS b
LEFT JOIN authors AS a
ON a.id = b.authorID;